
import type { Project, Service, TeamMember, Milestone } from './types';
import { ProjectCategory } from './types';
import { BuildingOffice2Icon, HomeModernIcon, WrenchScrewdriverIcon, PaintBrushIcon } from '@heroicons/react/24/outline';

export const NAV_LINKS = [
  { name: 'Home', path: '/' },
  { name: 'Services', path: '/services' },
  { name: 'About', path: '/about' },
  { name: 'Projects', path: '/projects' },
  { name: 'Contact Us', path: '/contact' },
];

export const SERVICES_DATA: Service[] = [
  {
    id: 's1',
    title: 'Architectural Design',
    icon: BuildingOffice2Icon,
    description: 'Innovative and sustainable architectural designs tailored to your vision.',
    details: ['Concept Development', '3D Modeling & Visualization', 'Construction Documents', 'Permit Assistance'],
  },
  {
    id: 's2',
    title: 'General Construction',
    icon: WrenchScrewdriverIcon,
    description: 'High-quality construction services from groundwork to finishing touches.',
    details: ['New Builds', 'Structural Engineering', 'Project Management', 'Quality Control'],
  },
  {
    id: 's3',
    title: 'Interior Decoration',
    icon: PaintBrushIcon,
    description: 'Creating beautiful and functional interior spaces that reflect your personality.',
    details: ['Space Planning', 'Material & Color Selection', 'Furniture Sourcing', 'Lighting Design'],
  },
  {
    id: 's4',
    title: 'Renovation & Remodeling',
    icon: HomeModernIcon,
    description: 'Transforming existing spaces to meet modern standards and styles.',
    details: ['Kitchen & Bath Remodeling', 'Home Additions', 'Historical Restoration', 'Energy Efficiency Upgrades'],
  },
];

export const PROJECTS_DATA: Project[] = [
  {
    id: 'p1',
    title: 'Modern Lakeside Villa',
    category: ProjectCategory.RESIDENTIAL,
    client: 'Mr. & Mrs. Smith',
    location: 'Geneva, Switzerland',
    cost: '$2.5 Million',
    timeline: '18 Months',
    shortDescription: 'A stunning lakeside property with panoramic views and minimalist design.',
    description: 'This project involved the ground-up construction of a contemporary villa on the shores of Lake Geneva. Key features include floor-to-ceiling windows, an open-plan living space, and sustainable energy solutions. The design seamlessly integrates the interior with the surrounding natural beauty.',
    coverImage: 'https://picsum.photos/seed/p1/800/600',
    gallery: ['https://picsum.photos/seed/p1-g1/1200/800', 'https://picsum.photos/seed/p1-g2/1200/800', 'https://picsum.photos/seed/p1-g3/1200/800'],
  },
  {
    id: 'p2',
    title: 'The Urban Eatery',
    category: ProjectCategory.HOSPITALITY,
    client: 'Gourmet Group Ltd.',
    location: 'New York, USA',
    cost: '$1.2 Million',
    timeline: '9 Months',
    shortDescription: 'A chic and rustic restaurant design in the heart of downtown.',
    description: 'We transformed a historic downtown building into a vibrant, modern restaurant. The project preserved original brickwork while introducing industrial-chic elements, custom lighting, and a state-of-the-art kitchen. The result is an inviting atmosphere that has become a local favorite.',
    coverImage: 'https://picsum.photos/seed/p2/800/600',
    gallery: ['https://picsum.photos/seed/p2-g1/1200/800', 'https://picsum.photos/seed/p2-g2/1200/800'],
  },
  {
    id: 'p3',
    title: 'Innovatech Corporate HQ',
    category: ProjectCategory.COMMERCIAL,
    client: 'Innovatech Solutions',
    location: 'Silicon Valley, USA',
    cost: '$15 Million',
    timeline: '24 Months',
    shortDescription: 'A futuristic and collaborative workspace for a leading tech company.',
    description: 'This project was the design and construction of a new headquarters for a major tech firm. It features collaborative workspaces, smart building technology, green rooftops, and an emphasis on employee wellness. The architecture reflects the company\'s innovative spirit.',
    coverImage: 'https://picsum.photos/seed/p3/800/600',
    gallery: ['https://picsum.photos/seed/p3-g1/1200/800', 'https://picsum.photos/seed/p3-g2/1200/800', 'https://picsum.photos/seed/p3-g3/1200/800', 'https://picsum.photos/seed/p3-g4/1200/800'],
  },
  {
    id: 'p4',
    title: 'Elysian Boutique Hotel',
    category: ProjectCategory.HOSPITALITY,
    client: 'Serenity Stays',
    location: 'Bali, Indonesia',
    cost: '$4 Million',
    timeline: '20 Months',
    shortDescription: 'A luxury boutique hotel blending modern design with traditional Balinese elements.',
    description: 'Nestled in the lush landscapes of Bali, the Elysian Boutique Hotel offers a tranquil retreat. Our team managed the entire project from architectural design to interior furnishing, focusing on local materials and craftsmanship to create an authentic yet luxurious guest experience.',
    coverImage: 'https://picsum.photos/seed/p4/800/600',
    gallery: ['https://picsum.photos/seed/p4-g1/1200/800', 'https://picsum.photos/seed/p4-g2/1200/800', 'https://picsum.photos/seed/p4-g3/1200/800'],
  },
   {
    id: 'p5',
    title: 'Oakridge Family Home',
    category: ProjectCategory.RESIDENTIAL,
    client: 'The Johnson Family',
    location: 'Vancouver, Canada',
    cost: '$1.8 Million',
    timeline: '14 Months',
    shortDescription: 'A warm and spacious family home with a focus on natural light and wood.',
    description: 'Designed for a growing family, this home prioritizes functionality and comfort. It features large open spaces, custom-built storage solutions, and a strong connection to the outdoors with a large deck and garden. The use of oak and cedar throughout creates a cozy, inviting atmosphere.',
    coverImage: 'https://picsum.photos/seed/p5/800/600',
    gallery: ['https://picsum.photos/seed/p5-g1/1200/800', 'https://picsum.photos/seed/p5-g2/1200/800'],
  },
   {
    id: 'p6',
    title: 'Sapphire Tower Offices',
    category: ProjectCategory.COMMERCIAL,
    client: 'Global Investments Inc.',
    location: 'Dubai, UAE',
    cost: '$8.2 Million',
    timeline: '16 Months',
    shortDescription: 'Premium office fit-out on the 45th floor of a prestigious skyscraper.',
    description: 'We executed a complete interior fit-out for three floors of the Sapphire Tower. The design boasts luxurious materials, cutting-edge technology integration for conference rooms, and panoramic city views from every office. The project was completed on a fast-track schedule without compromising quality.',
    coverImage: 'https://picsum.photos/seed/p6/800/600',
    gallery: ['https://picsum.photos/seed/p6-g1/1200/800', 'https://picsum.photos/seed/p6-g2/1200/800', 'https://picsum.photos/seed/p6-g3/1200/800'],
  },
  {
    id: 'p7',
    title: 'Future Leaders Academy',
    category: ProjectCategory.EDUCATIONAL,
    client: 'Board of Education',
    location: 'Helsinki, Finland',
    cost: '$12 Million',
    timeline: '30 Months',
    shortDescription: 'A state-of-the-art educational facility designed for modern learning.',
    description: 'This new academy campus was designed to foster collaboration and creativity. It includes flexible classrooms, science labs, a digital library, and extensive sports facilities. Sustainability was a core principle, incorporating solar panels, rainwater harvesting, and green building materials.',
    coverImage: 'https://picsum.photos/seed/p7/800/600',
    gallery: ['https://picsum.photos/seed/p7-g1/1200/800', 'https://picsum.photos/seed/p7-g2/1200/800'],
  },
  {
    id: 'p8',
    title: '"Vogue" Flagship Store',
    category: ProjectCategory.RETAIL,
    client: 'Vogue International',
    location: 'Paris, France',
    cost: '$3.5 Million',
    timeline: '8 Months',
    shortDescription: 'An elegant and immersive retail experience for a high-fashion brand.',
    description: 'Located on a prestigious Parisian street, this flagship store required a design that matched the brand\'s luxury status. We used marble, brass, and custom lighting to create a sophisticated ambiance. The layout is designed to guide customers through curated collections, enhancing the shopping experience.',
    coverImage: 'https://picsum.photos/seed/p8/800/600',
    gallery: ['https://picsum.photos/seed/p8-g1/1200/800', 'https://picsum.photos/seed/p8-g2/1200/800', 'https://picsum.photos/seed/p8-g3/1200/800'],
  },
];

export const TEAM_DATA: TeamMember[] = [
  { id: 't1', name: 'John Pasalka', role: 'Founder & CEO', photoUrl: 'https://picsum.photos/seed/t1/400/400' },
  { id: 't2', name: 'Jane Doe', role: 'Lead Architect', photoUrl: 'https://picsum.photos/seed/t2/400/400' },
  { id: 't3', name: 'Mike Richards', role: 'Head of Construction', photoUrl: 'https://picsum.photos/seed/t3/400/400' },
  { id: 't4', name: 'Sarah Chen', role: 'Creative Director, Interiors', photoUrl: 'https://picsum.photos/seed/t4/400/400' },
];

export const MILESTONES_DATA: Milestone[] = [
    { year: 2005, description: 'Pasalka Builders was founded with a focus on residential projects.' },
    { year: 2010, description: 'Expanded services to include commercial construction and completed our first major office project.' },
    { year: 2015, description: 'Opened our Interior Decoration division, offering end-to-end design solutions.' },
    { year: 2020, description: 'Won the "Excellence in Design" award for the Innovatech Corporate HQ project.' },
    { year: 2023, description: 'Expanded operations internationally, completing our first project in Europe.' },
]
